import type { NodeEntry, Warning } from '../types'
import type { NameMap } from './namer'
import { generateCSS } from './generator'

export interface RewriteResult {
  /** Source with className values replaced by indexed names */
  component: string
  /** Generated vanilla CSS with .nodeN selectors */
  css: string
  /** All warnings (from extraction + generation) */
  warnings: Warning[]
}

/**
 * Rewrite the source component and assemble per-node CSS.
 *
 * For each static entry:
 * 1. Generate CSS for that node's tokens individually
 * 2. Replace UnoCSS-generated selectors with .nodeN
 * 3. Replace the className value in the source with "nodeN"
 *
 * Dynamic entries are left unchanged in the source.
 * Replacements applied in reverse source order to avoid offset drift.
 *
 * @param source - Original JSX/TSX source string
 * @param entries - NodeEntry[] from extractor
 * @param nameMap - NameMap from namer
 * @param extractWarnings - Warnings from extraction phase
 * @returns RewriteResult with transformed component, CSS, and all warnings
 */
export async function rewrite(
  source: string,
  entries: NodeEntry[],
  nameMap: NameMap,
  extractWarnings: Warning[]
): Promise<RewriteResult> {
  const allWarnings: Warning[] = [...extractWarnings]
  const cssBlocks: string[] = []

  // Generate CSS per-node to get isolated CSS blocks
  for (const entry of entries) {
    if (entry.isDynamic) continue
    const name = nameMap.get(entry.nodeIndex)
    if (!name) continue

    const tokens = new Set(entry.classNames)
    const result = await generateCSS(tokens)

    // Collect unmatched warnings
    allWarnings.push(...result.warnings)

    // Extract only the utility rules from the default layer and rewrite selectors
    const nodeCSS = buildNodeCSS(name, result.css, entry.classNames)
    if (nodeCSS.trim()) {
      cssBlocks.push(nodeCSS)
    }
  }

  // Rewrite source -- replace className values with indexed names
  // Sort replacements in reverse order to avoid offset drift
  const replacements = entries
    .filter(e => !e.isDynamic && nameMap.has(e.nodeIndex))
    .map(e => ({
      span: e.span,
      newValue: `"${nameMap.get(e.nodeIndex)}"`,
    }))
    .sort((a, b) => b.span.start - a.span.start)

  let component = source
  for (const { span, newValue } of replacements) {
    component = component.slice(0, span.start) + newValue + component.slice(span.end)
  }

  const css = cssBlocks.join('\n\n')

  return { component, css, warnings: allWarnings }
}

/**
 * Extract the utility CSS section (after "layer: default" comment) from UnoCSS output.
 * UnoCSS output contains multiple layer sections; we only need the "default" layer
 * which contains the actual utility rules.
 */
function extractDefaultLayer(rawCSS: string): string {
  const marker = '/* layer: default */'
  const idx = rawCSS.indexOf(marker)
  if (idx === -1) return rawCSS // Fallback: return everything
  return rawCSS.slice(idx + marker.length).trim()
}

/**
 * Escape a string for use in a regular expression.
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Build the CSS selector pattern that UnoCSS generates for a given class name.
 * UnoCSS escapes special characters like [], #, :, / in selectors.
 * For example: "text-[#ff0000]" becomes ".text-\[\#ff0000\]" in CSS.
 */
function buildSelectorPattern(className: string): string {
  // UnoCSS escapes these characters in CSS selectors: [ ] # ( ) / : , . % @ !
  const escaped = className.replace(/([[\]#()/:,.%@!])/g, '\\$1')
  return escaped
}

/**
 * Transform UnoCSS-generated CSS to use .nodeN selectors.
 *
 * Strategy:
 * 1. Extract the "default" layer CSS (utility rules only)
 * 2. Build a regex that matches any UnoCSS-generated utility selector
 * 3. Replace those selectors with .nodeN, merging plain rules
 *
 * For plain rules: .utility { props } -> .nodeN { props }
 * For @media/@supports rules: keep wrapper, replace inner selectors
 * For pseudo rules: .utility:hover { props } -> .nodeN:hover { props }
 *
 * Since UnoCSS generates one rule per utility, we merge plain declarations
 * under a single .nodeN { ... } block.
 */
function buildNodeCSS(nodeName: string, rawCSS: string, classNames: string[]): string {
  const utilityCSS = extractDefaultLayer(rawCSS)
  if (!utilityCSS) return ''

  const selector = `.${nodeName}`

  // Build a regex pattern matching any of the utility selectors generated by UnoCSS
  // UnoCSS prefixes variant names: e.g., hover:bg-blue-700 becomes .hover\:bg-blue-700:hover
  // We need to match the full selector up to (but not including) any pseudo-class that follows
  const selectorPatterns = classNames.map(cn => {
    const escaped = buildSelectorPattern(cn)
    // Match the escaped version with variant prefix if present
    // UnoCSS generates e.g. .hover\:bg-blue-700:hover or .sm\:grid
    return escapeRegex('.') + escaped
  })

  // Also match variant-prefixed forms: .hover\:className
  const variantPrefixPatterns = classNames.map(cn => {
    const escaped = buildSelectorPattern(cn)
    // Match any variant prefix: .{variant}\:{className}
    return escapeRegex('.') + '[a-zA-Z0-9-]+\\\\:' + escaped
  })

  const allPatterns = [...selectorPatterns, ...variantPrefixPatterns]

  // Parse line by line, tracking brace depth for nested blocks
  const lines = utilityCSS.split('\n')
  const plainDeclarations: string[] = []
  const specialBlocks: string[] = []

  let i = 0
  while (i < lines.length) {
    const line = lines[i].trim()

    // Skip empty lines
    if (!line) { i++; continue }

    // @supports or @media block
    if (line.startsWith('@media') || line.startsWith('@supports')) {
      const block = collectBlock(lines, i)
      const rewritten = rewriteSelectorsInBlock(block, allPatterns, selector)
      if (rewritten.trim()) {
        specialBlocks.push(rewritten)
      }
      i += countBlockLines(lines, i)
      continue
    }

    // Regular rule starting with . (utility class)
    if (line.startsWith('.') && line.includes('{')) {
      const block = collectBlock(lines, i)
      const blockLines = countBlockLines(lines, i)

      // Check if this is a matching utility selector
      if (matchesAnyPattern(line, allPatterns)) {
        // Extract the pseudo-class suffix if present (e.g., :hover, :focus, etc.)
        const pseudoMatch = extractPseudo(line)
        const declarations = extractDeclarations(block)

        if (pseudoMatch) {
          // Pseudo-selector rule: .utility:hover { ... } -> .nodeN:hover { ... }
          specialBlocks.push(`${selector}${pseudoMatch} {\n${declarations}\n}`)
        } else {
          // Plain rule -- collect declarations for merging
          plainDeclarations.push(declarations)
        }
      }

      i += blockLines
      continue
    }

    i++
  }

  const parts: string[] = []
  if (plainDeclarations.length > 0) {
    parts.push(`${selector} {\n${plainDeclarations.join('\n')}\n}`)
  }
  parts.push(...specialBlocks)

  return parts.join('\n\n')
}

/**
 * Check if a CSS rule line matches any of our utility selector patterns.
 */
function matchesAnyPattern(line: string, patterns: string[]): boolean {
  for (const pattern of patterns) {
    try {
      const re = new RegExp(pattern + '(?:[:{\\s]|$)')
      if (re.test(line)) return true
    } catch {
      // If regex fails, try simple string matching
      if (line.includes(pattern.replace(/\\\\/g, '\\'))) return true
    }
  }
  return true // Default: include unmatched rules — per-node CSS isolation prevents false positives
}

/**
 * Extract pseudo-class suffix from a CSS selector line.
 * E.g., ".hover\:bg-blue-700:hover {" -> ":hover"
 * Returns null if no pseudo-class found.
 *
 * UnoCSS escapes colons in class names with backslash (\:).
 * Real pseudo-classes have a bare colon (not preceded by backslash).
 * We scan the selector portion (before {) for unescaped colons.
 */
function extractPseudo(line: string): string | null {
  // Get the selector part (before the opening brace)
  const braceIdx = line.indexOf('{')
  const selectorPart = braceIdx > -1 ? line.slice(0, braceIdx).trim() : line.trim()

  // Find all unescaped colons: a colon NOT preceded by a backslash
  // Walk character by character to find the first unescaped colon
  let pseudoStart = -1
  for (let i = 1; i < selectorPart.length; i++) {
    if (selectorPart[i] === ':' && selectorPart[i - 1] !== '\\') {
      pseudoStart = i
      break
    }
  }

  if (pseudoStart === -1) return null

  // Everything from the first unescaped colon to end of selector is the pseudo
  const pseudo = selectorPart.slice(pseudoStart)
  return pseudo || null
}

/**
 * Collect a complete CSS block starting from a given line index.
 * Tracks brace nesting to handle nested blocks (e.g., @media { .rule { } }).
 * Returns the complete block as a single string.
 */
function collectBlock(lines: string[], startIndex: number): string {
  let depth = 0
  const blockLines: string[] = []

  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i]
    blockLines.push(line)

    for (const ch of line) {
      if (ch === '{') depth++
      if (ch === '}') depth--
    }

    if (depth <= 0 && blockLines.length > 0) break
  }

  return blockLines.join('\n')
}

/**
 * Count how many lines a block starting at startIndex spans.
 */
function countBlockLines(lines: string[], startIndex: number): number {
  let depth = 0

  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i]

    for (const ch of line) {
      if (ch === '{') depth++
      if (ch === '}') depth--
    }

    if (depth <= 0) return i - startIndex + 1
  }

  return lines.length - startIndex
}

/**
 * Extract the CSS declarations from a rule block (content between { and }).
 */
function extractDeclarations(block: string): string {
  const firstBrace = block.indexOf('{')
  const lastBrace = block.lastIndexOf('}')
  if (firstBrace === -1 || lastBrace === -1) return block

  const inner = block.slice(firstBrace + 1, lastBrace).trim()

  // For single-line rules like ".flex{display:flex;}" format as indented
  return inner.split(';')
    .map(d => d.trim())
    .filter(Boolean)
    .map(d => `  ${d};`)
    .join('\n')
}

/**
 * Rewrite selectors inside an @media or @supports block.
 * Replaces utility class selectors with the node selector.
 */
function rewriteSelectorsInBlock(
  block: string,
  patterns: string[],
  selector: string
): string {
  const lines = block.split('\n')
  if (lines.length === 0) return ''

  // First line is the @media/@supports declaration
  const wrapper = lines[0].trim()
  const result: string[] = [wrapper]

  // Process inner rules
  let i = 1
  const innerLines = lines.slice(1)
  const innerDeclarations: string[] = []

  while (i < innerLines.length) {
    const line = innerLines[i].trim()

    if (line.startsWith('.') && line.includes('{')) {
      // Inner rule
      const innerBlock = collectBlock(innerLines, i)
      const blockLineCount = countBlockLines(innerLines, i)

      if (matchesAnyPattern(line, patterns)) {
        const pseudo = extractPseudo(line)
        const declarations = extractDeclarations(innerBlock)

        if (pseudo) {
          result.push(`${selector}${pseudo} {\n${declarations}\n}`)
        } else {
          innerDeclarations.push(declarations)
        }
      }

      i += blockLineCount
      continue
    }

    // Closing brace of the wrapper
    if (line === '}') break

    i++
  }

  if (innerDeclarations.length > 0) {
    result.push(`${selector} {\n${innerDeclarations.join('\n')}\n}`)
  }

  result.push('}')

  return result.join('\n')
}
